version: "3.2"
services:
  parity:
    image: makerdao/testchain-pymaker:unit-testing
    container_name: parity-pymaker-test
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
    user: root
    working_dir: /home/parity

